### ISSUE TITLE
Mettre en place le MVC

### ISSUE THREAD

**Issue by NicolasMugnier** [florentingarnier/OC_p3#3]
- implémenter l'autoloader
- implémenter le router (une méthode dispatch(Request $request, Response $response)) si controller ou méthode inexistante -> 404
- implémenter un controller

lors de l'appel à l'url : localhost?controller=index?pseudo=toto affichage d'une page simple contenant <h1>hello $pseudo</h1>

**Comment by FlorentinGarnier** [comment]
Ok
